/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 28 04:24:23 GMT 2022
 */

package com.eteks.sweethome3d.swing;

import org.junit.Test;
import static org.junit.Assert.*;
import com.eteks.sweethome3d.io.DefaultUserPreferences;
import com.eteks.sweethome3d.io.FileUserPreferences;
import com.eteks.sweethome3d.swing.FontNameComboBox;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FontNameComboBox_ESTest extends FontNameComboBox_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultUserPreferences defaultUserPreferences0 = new DefaultUserPreferences();
      FontNameComboBox fontNameComboBox0 = new FontNameComboBox(defaultUserPreferences0);
      fontNameComboBox0.setSelectedItem("Language library");
      fontNameComboBox0.setSelectedItem("Textures library");
      assertFalse(fontNameComboBox0.isFocusCycleRoot());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FileUserPreferences fileUserPreferences0 = new FileUserPreferences();
      FontNameComboBox fontNameComboBox0 = new FontNameComboBox(fileUserPreferences0);
      fontNameComboBox0.setSelectedItem("Agency FB");
      assertFalse(fontNameComboBox0.isFocusTraversalPolicySet());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultUserPreferences defaultUserPreferences0 = new DefaultUserPreferences();
      FontNameComboBox fontNameComboBox0 = new FontNameComboBox(defaultUserPreferences0);
      fontNameComboBox0.getTopLevelAncestor();
      fontNameComboBox0.setSelectedItem((Object) null);
      fontNameComboBox0.setSelectedItem(defaultUserPreferences0);
      fontNameComboBox0.setSelectedItem((Object) null);
  }
}
