/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 28 04:25:41 GMT 2022
 */

package com.eteks.sweethome3d.swing;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.eteks.sweethome3d.io.DefaultUserPreferences;
import com.eteks.sweethome3d.model.FurnitureCatalog;
import com.eteks.sweethome3d.swing.FurnitureCatalogListPanel;
import com.eteks.sweethome3d.viewcontroller.FurnitureCatalogController;
import com.eteks.sweethome3d.viewcontroller.ViewFactoryAdapter;
import java.awt.HeadlessException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FurnitureCatalogListPanel_ESTest extends FurnitureCatalogListPanel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FurnitureCatalog furnitureCatalog0 = new FurnitureCatalog();
      DefaultUserPreferences defaultUserPreferences0 = new DefaultUserPreferences();
      ViewFactoryAdapter viewFactoryAdapter0 = new ViewFactoryAdapter();
      FurnitureCatalogController furnitureCatalogController0 = new FurnitureCatalogController(furnitureCatalog0, viewFactoryAdapter0);
      FurnitureCatalogListPanel furnitureCatalogListPanel0 = null;
      try {
        furnitureCatalogListPanel0 = new FurnitureCatalogListPanel(furnitureCatalog0, defaultUserPreferences0, furnitureCatalogController0);
        fail("Expecting exception: HeadlessException");
      
      } catch(HeadlessException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.swing.JList", e);
      }
  }
}
