/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Apr 28 02:51:49 GMT 2022
 */

package com.eteks.sweethome3d.applet;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class HomeAppletRecorder_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.eteks.sweethome3d.applet.HomeAppletRecorder"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Petros\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Petros\\Downloads\\CS520\\finalProject\\SweetHomeEvoSuite"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Petros"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Petros"); 
    java.lang.System.setProperty("user.timezone", "America/New_York"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(HomeAppletRecorder_ESTest_scaffolding.class.getClassLoader() ,
      "com.eteks.sweethome3d.model.HomeLight",
      "com.eteks.sweethome3d.model.CatalogItem",
      "com.eteks.sweethome3d.model.LengthUnit$1",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$SortableProperty",
      "com.eteks.sweethome3d.tools.SimpleURLContent",
      "com.eteks.sweethome3d.model.LengthUnit$SquareMeterAreaFormatWithUnit",
      "com.eteks.sweethome3d.io.FileUserPreferences$PortablePreferences",
      "com.eteks.sweethome3d.model.CollectionListener",
      "com.eteks.sweethome3d.io.DefaultHomeOutputStream$1",
      "com.eteks.sweethome3d.model.HomeEnvironment$Property",
      "com.eteks.sweethome3d.model.LengthUnit$2",
      "com.eteks.sweethome3d.model.LengthUnit$3",
      "com.eteks.sweethome3d.model.Home$Property",
      "com.eteks.sweethome3d.model.LengthUnit$4",
      "com.eteks.sweethome3d.model.LengthUnit$5",
      "com.eteks.sweethome3d.io.DefaultHomeInputStream",
      "com.eteks.sweethome3d.model.UserPreferences$Property",
      "com.eteks.sweethome3d.io.DefaultHomeOutputStream",
      "com.eteks.sweethome3d.model.HomeTexture",
      "com.eteks.sweethome3d.model.Camera$Lens",
      "com.eteks.sweethome3d.model.HomeEnvironment$DrawingMode",
      "com.eteks.sweethome3d.model.TexturesCatalog",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$9",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$8",
      "com.eteks.sweethome3d.model.TextStyle$Alignment",
      "com.eteks.sweethome3d.model.TexturesCategory",
      "com.eteks.sweethome3d.tools.OperatingSystem$4",
      "com.eteks.sweethome3d.model.CatalogTexture",
      "com.eteks.sweethome3d.tools.OperatingSystem$2",
      "com.eteks.sweethome3d.io.DamagedHomeIOException",
      "com.eteks.sweethome3d.tools.OperatingSystem$3",
      "com.eteks.sweethome3d.model.BackgroundImage",
      "com.eteks.sweethome3d.io.ContentRecording",
      "com.eteks.sweethome3d.model.Elevatable",
      "com.eteks.sweethome3d.model.CollectionChangeSupport",
      "com.eteks.sweethome3d.io.FileUserPreferences",
      "com.eteks.sweethome3d.model.LengthUnit$SquareFootAreaFormatWithUnit",
      "com.eteks.sweethome3d.model.Level$Property",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$5",
      "com.eteks.sweethome3d.model.SelectionListener",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$4",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$7",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$6",
      "com.eteks.sweethome3d.io.DefaultTexturesCatalog$PropertyKey",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$1",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$3",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$2",
      "com.eteks.sweethome3d.model.SelectionEvent",
      "com.eteks.sweethome3d.model.Polyline$CapStyle",
      "com.eteks.sweethome3d.model.DimensionLine",
      "com.eteks.sweethome3d.model.DoorOrWindow",
      "com.eteks.sweethome3d.io.HomeXMLExporter",
      "com.eteks.sweethome3d.model.LengthUnit$MeterFamilyFormat",
      "com.eteks.sweethome3d.io.DefaultUserPreferences",
      "com.eteks.sweethome3d.io.HomeXMLHandler",
      "com.eteks.sweethome3d.applet.HomeAppletRecorder$LengthOutputStream",
      "com.eteks.sweethome3d.model.Wall",
      "com.eteks.sweethome3d.model.DimensionLine$Property",
      "com.eteks.sweethome3d.model.HomeEnvironment",
      "com.eteks.sweethome3d.model.HomePrint",
      "com.eteks.sweethome3d.model.UserPreferences",
      "com.eteks.sweethome3d.io.DefaultFurnitureCatalog",
      "com.eteks.sweethome3d.model.HomeObject",
      "com.eteks.sweethome3d.model.Room",
      "com.eteks.sweethome3d.model.AspectRatio",
      "com.eteks.sweethome3d.io.FileUserPreferences$4$3",
      "com.eteks.sweethome3d.model.Label",
      "com.eteks.sweethome3d.io.FileUserPreferences$4$1",
      "com.eteks.sweethome3d.model.Selectable",
      "com.eteks.sweethome3d.model.Polyline$JoinStyle",
      "com.eteks.sweethome3d.model.Wall$Property",
      "com.eteks.sweethome3d.io.HomeURLContent",
      "com.eteks.sweethome3d.model.Home",
      "com.eteks.sweethome3d.model.Polyline",
      "com.eteks.sweethome3d.model.HomeFurnitureGroup",
      "com.eteks.sweethome3d.model.InterruptedRecorderException",
      "com.eteks.sweethome3d.io.DefaultTexturesCatalog",
      "com.eteks.sweethome3d.model.LightSource",
      "com.eteks.sweethome3d.model.Polyline$ArrowStyle",
      "com.eteks.sweethome3d.model.LengthUnit",
      "com.eteks.sweethome3d.model.CatalogDoorOrWindow",
      "com.eteks.sweethome3d.model.CollectionEvent$Type",
      "com.eteks.sweethome3d.tools.ResourceURLContent",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$10",
      "com.eteks.sweethome3d.model.Compass$Property",
      "com.eteks.sweethome3d.model.CatalogLight",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$15",
      "com.eteks.sweethome3d.io.DefaultHomeOutputStream$HomeObjectOutputStream",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$16",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$17",
      "com.eteks.sweethome3d.model.Content",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$18",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$11",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$12",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$13",
      "com.eteks.sweethome3d.model.Light",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$14",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture",
      "com.eteks.sweethome3d.model.Label$Property",
      "com.eteks.sweethome3d.model.Compass$GeographicPoint",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$19",
      "com.eteks.sweethome3d.model.HomeRecorder",
      "com.eteks.sweethome3d.model.Home$4",
      "com.eteks.sweethome3d.model.Home$3",
      "com.eteks.sweethome3d.model.Home$2",
      "com.eteks.sweethome3d.model.Home$1",
      "com.eteks.sweethome3d.io.DefaultPatternTexture",
      "com.eteks.sweethome3d.io.FileUserPreferences$5$1",
      "com.eteks.sweethome3d.io.FileUserPreferences$5$3",
      "com.eteks.sweethome3d.io.HomeXMLExporter$1",
      "com.eteks.sweethome3d.io.HomeXMLExporter$4",
      "com.eteks.sweethome3d.io.HomeXMLExporter$5",
      "com.eteks.sweethome3d.io.FileUserPreferences$6",
      "com.eteks.sweethome3d.io.DefaultHomeInputStream$CopiedInputStream",
      "com.eteks.sweethome3d.io.DefaultFurnitureCatalog$PropertyKey",
      "com.eteks.sweethome3d.model.HomePrint$PaperOrientation",
      "com.eteks.sweethome3d.io.FileUserPreferences$4",
      "com.eteks.sweethome3d.model.UserPreferences$PrefixedResourceBundle",
      "com.eteks.sweethome3d.io.FileUserPreferences$5",
      "com.eteks.sweethome3d.io.FileUserPreferences$2",
      "com.eteks.sweethome3d.io.ResourceBundleTools$1",
      "com.eteks.sweethome3d.io.FileUserPreferences$3",
      "com.eteks.sweethome3d.model.FurnitureCatalog",
      "com.eteks.sweethome3d.io.FileUserPreferences$1",
      "com.eteks.sweethome3d.model.Sash",
      "com.eteks.sweethome3d.model.Library",
      "com.eteks.sweethome3d.model.Camera$Property",
      "com.eteks.sweethome3d.tools.TemporaryURLContent",
      "com.eteks.sweethome3d.model.TextureImage",
      "com.eteks.sweethome3d.model.Baseboard",
      "com.eteks.sweethome3d.model.TextStyle",
      "com.eteks.sweethome3d.io.DefaultHomeOutputStream$HomeContentObjectsTracker",
      "com.eteks.sweethome3d.model.CollectionEvent",
      "com.eteks.sweethome3d.model.UserPreferences$1",
      "com.eteks.sweethome3d.io.HomeContentContext",
      "com.eteks.sweethome3d.applet.AppletUserPreferences$1",
      "com.eteks.sweethome3d.io.ObjectXMLExporter",
      "com.eteks.sweethome3d.tools.URLContent",
      "com.eteks.sweethome3d.model.LengthUnit$4$1",
      "com.eteks.sweethome3d.model.HomeDoorOrWindow",
      "com.eteks.sweethome3d.applet.AppletUserPreferences",
      "com.eteks.sweethome3d.applet.AppletUserPreferences$4",
      "com.eteks.sweethome3d.applet.AppletUserPreferences$5",
      "com.eteks.sweethome3d.applet.AppletUserPreferences$2",
      "com.eteks.sweethome3d.applet.AppletUserPreferences$3",
      "com.eteks.sweethome3d.model.Transformation",
      "com.eteks.sweethome3d.model.Compass",
      "com.eteks.sweethome3d.model.HomeDescriptor",
      "com.eteks.sweethome3d.io.XMLWriter",
      "com.eteks.sweethome3d.io.ContentDigestManager",
      "com.eteks.sweethome3d.model.LengthUnit$5$1InchDecimalsFormat",
      "com.eteks.sweethome3d.model.FurnitureCategory",
      "com.eteks.sweethome3d.model.Camera",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$20",
      "com.eteks.sweethome3d.io.DefaultTexturesCatalog$2",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$21",
      "com.eteks.sweethome3d.io.DefaultTexturesCatalog$1",
      "com.eteks.sweethome3d.io.FileUserPreferences$PreferencesURLContent",
      "com.eteks.sweethome3d.model.PatternsCatalog",
      "com.eteks.sweethome3d.model.PieceOfFurniture",
      "com.eteks.sweethome3d.model.Polyline$DashStyle",
      "com.eteks.sweethome3d.model.ObserverCamera",
      "com.eteks.sweethome3d.model.RecorderException",
      "com.eteks.sweethome3d.model.Level",
      "com.eteks.sweethome3d.tools.OperatingSystem",
      "com.eteks.sweethome3d.applet.HomeAppletRecorder",
      "com.eteks.sweethome3d.io.ResourceBundleTools",
      "com.eteks.sweethome3d.model.CatalogPieceOfFurniture",
      "com.eteks.sweethome3d.model.HomeMaterial",
      "com.eteks.sweethome3d.io.DefaultFurnitureCatalog$2",
      "com.eteks.sweethome3d.io.DefaultFurnitureCatalog$1"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(HomeAppletRecorder_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.eteks.sweethome3d.applet.HomeAppletRecorder",
      "com.eteks.sweethome3d.applet.HomeAppletRecorder$LengthOutputStream",
      "com.eteks.sweethome3d.io.ContentRecording",
      "com.eteks.sweethome3d.io.ObjectXMLExporter",
      "com.eteks.sweethome3d.io.HomeXMLExporter",
      "com.eteks.sweethome3d.model.Home$1",
      "com.eteks.sweethome3d.model.Home",
      "com.eteks.sweethome3d.model.CollectionChangeSupport",
      "com.eteks.sweethome3d.model.HomeObject",
      "com.eteks.sweethome3d.model.Camera",
      "com.eteks.sweethome3d.model.ObserverCamera",
      "com.eteks.sweethome3d.model.HomeEnvironment",
      "com.eteks.sweethome3d.model.HomeEnvironment$DrawingMode",
      "com.eteks.sweethome3d.model.AspectRatio",
      "com.eteks.sweethome3d.model.Compass",
      "com.eteks.sweethome3d.model.Compass$GeographicPoint",
      "com.eteks.sweethome3d.model.Home$2",
      "com.eteks.sweethome3d.model.Home$3",
      "com.eteks.sweethome3d.io.DefaultHomeOutputStream",
      "com.eteks.sweethome3d.io.DefaultHomeOutputStream$HomeContentObjectsTracker",
      "com.eteks.sweethome3d.io.DefaultHomeOutputStream$1",
      "com.eteks.sweethome3d.model.CollectionEvent$Type",
      "com.eteks.sweethome3d.model.Home$4",
      "com.eteks.sweethome3d.io.DefaultHomeOutputStream$HomeObjectOutputStream",
      "com.eteks.sweethome3d.model.Label",
      "com.eteks.sweethome3d.model.RecorderException",
      "com.eteks.sweethome3d.model.Wall",
      "com.eteks.sweethome3d.io.HomeXMLHandler",
      "com.eteks.sweethome3d.model.TextStyle",
      "com.eteks.sweethome3d.model.TextStyle$Alignment",
      "com.eteks.sweethome3d.model.UserPreferences",
      "com.eteks.sweethome3d.io.DefaultUserPreferences",
      "com.eteks.sweethome3d.model.FurnitureCatalog",
      "com.eteks.sweethome3d.model.TexturesCatalog",
      "com.eteks.sweethome3d.io.DefaultPatternTexture",
      "com.eteks.sweethome3d.tools.URLContent",
      "com.eteks.sweethome3d.tools.ResourceURLContent",
      "com.eteks.sweethome3d.model.PatternsCatalog",
      "com.eteks.sweethome3d.model.UserPreferences$1",
      "com.eteks.sweethome3d.model.LengthUnit",
      "com.eteks.sweethome3d.model.HomeDescriptor",
      "com.eteks.sweethome3d.io.FileUserPreferences$PreferencesURLContent",
      "com.eteks.sweethome3d.io.FileUserPreferences",
      "com.eteks.sweethome3d.io.FileUserPreferences$1",
      "com.eteks.sweethome3d.io.FileUserPreferences$3",
      "com.eteks.sweethome3d.io.FileUserPreferences$PortablePreferences",
      "com.eteks.sweethome3d.io.FileUserPreferences$4",
      "com.eteks.sweethome3d.io.FileUserPreferences$4$1",
      "com.eteks.sweethome3d.io.DefaultFurnitureCatalog",
      "com.eteks.sweethome3d.io.DefaultFurnitureCatalog$2",
      "com.eteks.sweethome3d.io.DefaultFurnitureCatalog$PropertyKey",
      "com.eteks.sweethome3d.io.DefaultFurnitureCatalog$1",
      "com.eteks.sweethome3d.io.FileUserPreferences$4$3",
      "com.eteks.sweethome3d.io.FileUserPreferences$5",
      "com.eteks.sweethome3d.io.FileUserPreferences$5$1",
      "com.eteks.sweethome3d.io.DefaultTexturesCatalog",
      "com.eteks.sweethome3d.io.DefaultTexturesCatalog$2",
      "com.eteks.sweethome3d.io.DefaultTexturesCatalog$PropertyKey",
      "com.eteks.sweethome3d.io.DefaultTexturesCatalog$1",
      "com.eteks.sweethome3d.io.FileUserPreferences$5$3",
      "com.eteks.sweethome3d.io.FileUserPreferences$2",
      "com.eteks.sweethome3d.applet.AppletUserPreferences",
      "com.eteks.sweethome3d.applet.AppletUserPreferences$1",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$1",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$2",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$3",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$4",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$5",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$6",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$7",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$8",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$9",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$10",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$11",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$12",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$13",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$14",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$15",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$16",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$17",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$18",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$19",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$20",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$21",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture",
      "com.eteks.sweethome3d.model.HomeFurnitureGroup",
      "com.eteks.sweethome3d.io.XMLWriter",
      "com.eteks.sweethome3d.io.HomeXMLExporter$1",
      "com.eteks.sweethome3d.io.HomeXMLExporter$4",
      "com.eteks.sweethome3d.io.HomeXMLExporter$5",
      "com.eteks.sweethome3d.tools.OperatingSystem",
      "com.eteks.sweethome3d.model.Room",
      "com.eteks.sweethome3d.applet.AppletUserPreferences$4",
      "com.eteks.sweethome3d.io.ResourceBundleTools",
      "com.eteks.sweethome3d.applet.AppletUserPreferences$5",
      "com.eteks.sweethome3d.applet.AppletUserPreferences$2",
      "com.eteks.sweethome3d.applet.AppletUserPreferences$3",
      "com.eteks.sweethome3d.model.DimensionLine",
      "com.eteks.sweethome3d.model.DimensionLine$Property",
      "com.eteks.sweethome3d.model.HomePrint",
      "com.eteks.sweethome3d.model.CatalogPieceOfFurniture",
      "com.eteks.sweethome3d.model.CatalogLight",
      "com.eteks.sweethome3d.model.Polyline",
      "com.eteks.sweethome3d.model.Label$Property",
      "com.eteks.sweethome3d.model.CatalogTexture",
      "com.eteks.sweethome3d.model.HomeTexture",
      "com.eteks.sweethome3d.io.FileUserPreferences$6",
      "com.eteks.sweethome3d.tools.SimpleURLContent",
      "com.eteks.sweethome3d.model.BackgroundImage",
      "com.eteks.sweethome3d.io.ContentDigestManager",
      "com.eteks.sweethome3d.model.HomeLight",
      "com.eteks.sweethome3d.model.Level",
      "com.eteks.sweethome3d.tools.TemporaryURLContent",
      "com.eteks.sweethome3d.tools.OperatingSystem$2",
      "com.eteks.sweethome3d.tools.OperatingSystem$3",
      "com.eteks.sweethome3d.model.LightSource",
      "com.eteks.sweethome3d.model.Sash",
      "com.eteks.sweethome3d.model.CatalogDoorOrWindow",
      "com.eteks.sweethome3d.model.HomeDoorOrWindow",
      "com.eteks.sweethome3d.model.Wall$Property",
      "com.eteks.sweethome3d.model.Level$Property",
      "com.eteks.sweethome3d.model.CollectionEvent",
      "com.eteks.sweethome3d.model.Compass$Property",
      "com.eteks.sweethome3d.model.PieceOfFurniture",
      "com.eteks.sweethome3d.model.UserPreferences$Property",
      "com.eteks.sweethome3d.model.HomePieceOfFurniture$SortableProperty",
      "com.eteks.sweethome3d.model.Camera$Lens"
    );
  }
}
