/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 28 03:40:48 GMT 2022
 */

package com.eteks.sweethome3d.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.eteks.sweethome3d.model.CatalogTexture;
import com.eteks.sweethome3d.model.Content;
import com.eteks.sweethome3d.model.HomeMaterial;
import com.eteks.sweethome3d.model.HomeTexture;
import com.eteks.sweethome3d.tools.ResourceURLContent;
import com.eteks.sweethome3d.tools.SimpleURLContent;
import java.net.URL;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HomeMaterial_ESTest extends HomeMaterial_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CatalogTexture catalogTexture0 = new CatalogTexture("6s$>E*+^Y;g!`o28", (Content) null, (-1.0F), (-1.0F), false);
      HomeTexture homeTexture0 = new HomeTexture(catalogTexture0, (-1.0F), false);
      Float float0 = new Float(0.0F);
      HomeMaterial homeMaterial0 = new HomeMaterial("com.eteks.sweethome3d.model.HomeMaterial", (Integer) null, homeTexture0, float0);
      Float float1 = new Float(0.0F);
      HomeMaterial homeMaterial1 = new HomeMaterial("com.eteks.sweethome3d.model.HomeMaterial", (String) null, (Integer) null, homeTexture0, float1);
      boolean boolean0 = homeMaterial0.equals(homeMaterial1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CatalogTexture catalogTexture0 = new CatalogTexture("$exZ_Be87#2", "com.eteks.sweethome3d.model.HomeMaterial", (Content) null, (-13.379833F), (-13.379833F), "com.eteks.sweethome3d.model.HomeMaterial");
      HomeTexture homeTexture0 = new HomeTexture(catalogTexture0, (-13.379833F), (-13.379833F), (-13.379833F), 3305.772F, false, false);
      Float float0 = Float.valueOf(3305.772F);
      HomeMaterial homeMaterial0 = new HomeMaterial("com.eteks.sweethome3d.model.HomeMaterial", "com.eteks.sweethome3d.model.HomeMaterial", (Integer) null, homeTexture0, float0);
      HomeMaterial homeMaterial1 = new HomeMaterial("com.eteks.sweethome3d.model.HomeMaterial", "com.eteks.sweethome3d.model.HomeMaterial", (Integer) null, homeTexture0, (Float) null);
      boolean boolean0 = homeMaterial0.equals(homeMaterial1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer integer0 = new Integer(4426);
      Float float0 = new Float(0.0F);
      HomeMaterial homeMaterial0 = new HomeMaterial("Ms&UykjHJ", integer0, (HomeTexture) null, float0);
      Float float1 = new Float((double) 4426);
      HomeMaterial homeMaterial1 = new HomeMaterial("Ms&UykjHJ", "Ms&UykjHJ", integer0, (HomeTexture) null, float1);
      boolean boolean0 = homeMaterial0.equals(homeMaterial1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CatalogTexture catalogTexture0 = new CatalogTexture(" me\"y1qp[[VFA", " me\"y1qp[[VFA", (Content) null, 0.0F, 0.0F, " me\"y1qp[[VFA");
      HomeTexture homeTexture0 = new HomeTexture(catalogTexture0, 0.0F, true);
      Float float0 = new Float(0.0F);
      HomeMaterial homeMaterial0 = new HomeMaterial(" me\"y1qp[[VFA", (Integer) null, homeTexture0, float0);
      HomeTexture homeTexture1 = new HomeTexture(catalogTexture0);
      HomeMaterial homeMaterial1 = new HomeMaterial(" me\"y1qp[[VFA", (Integer) null, homeTexture1, float0);
      boolean boolean0 = homeMaterial0.equals(homeMaterial1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CatalogTexture catalogTexture0 = new CatalogTexture("com.etek9.sweethome3d.model.HomMaterial", (Content) null, (-33.955696F), (-33.955696F));
      HomeTexture homeTexture0 = new HomeTexture(catalogTexture0, (-33.955696F), (-33.955696F), (-33.955696F), (-33.955696F), false, false);
      Float float0 = new Float((-33.955696F));
      HomeMaterial homeMaterial0 = new HomeMaterial("com.etek9.sweethome3d.model.HomMaterial", (Integer) null, homeTexture0, float0);
      HomeMaterial homeMaterial1 = new HomeMaterial("com.etek9.sweethome3d.model.HomMaterial", (String) null, (Integer) null, (HomeTexture) null, float0);
      boolean boolean0 = homeMaterial0.equals(homeMaterial1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CatalogTexture catalogTexture0 = new CatalogTexture("cw'n)l>qR:cF.8", (Content) null, (-1.0F), (-1.0F));
      HomeTexture homeTexture0 = new HomeTexture(catalogTexture0, (-907.80536F), (-4265.3955F), (-907.80536F), 3305.3F, true, true);
      Float float0 = Float.valueOf(0.0F);
      HomeMaterial homeMaterial0 = new HomeMaterial("com.eteks.sweethome3d.model.HomeMaterial", "com.eteks.sweethome3d.model.HomeMaterial", (Integer) null, homeTexture0, float0);
      HomeTexture homeTexture1 = new HomeTexture(homeTexture0, (-4265.3955F), (-4265.3955F), false);
      HomeMaterial homeMaterial1 = new HomeMaterial("com.eteks.sweethome3d.model.HomeMaterial", "com.eteks.sweethome3d.model.HomeMaterial", (Integer) null, homeTexture1, (Float) null);
      boolean boolean0 = homeMaterial0.equals(homeMaterial1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Integer integer0 = new Integer(4426);
      Float float0 = new Float(0.0F);
      HomeMaterial homeMaterial0 = new HomeMaterial("Ms&UykjHJ", integer0, (HomeTexture) null, float0);
      Integer integer1 = new Integer(4426);
      HomeMaterial homeMaterial1 = new HomeMaterial("Ms&UykjHJ", "Ms&UykjHJ", integer1, (HomeTexture) null, float0);
      boolean boolean0 = homeMaterial0.equals(homeMaterial1);
      assertTrue(boolean0);
      assertFalse(homeMaterial1.equals((Object)homeMaterial0));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CatalogTexture catalogTexture0 = new CatalogTexture("com.eteks.sweethome3d.tools.URLContent", (Content) null, (-1.0F), (-1.0F));
      HomeTexture homeTexture0 = new HomeTexture(catalogTexture0, (-1.0F), (-2548.4663F), (-2548.4663F), (-1126.0F), false);
      Float float0 = new Float((-1.0F));
      HomeMaterial homeMaterial0 = new HomeMaterial("com.eteks.sweethome3d.tools.URLContent", (Integer) null, homeTexture0, float0);
      Integer integer0 = new Integer(557);
      HomeMaterial homeMaterial1 = new HomeMaterial("com.eteks.sweethome3d.tools.URLContent", integer0, homeTexture0, float0);
      boolean boolean0 = homeMaterial1.equals(homeMaterial0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CatalogTexture catalogTexture0 = new CatalogTexture("com.eteks.sweethome3d.tools.URLContent", (Content) null, (-1.0F), (-1.0F));
      HomeTexture homeTexture0 = new HomeTexture(catalogTexture0, (-1.0F), (-2548.4663F), (-2548.4663F), (-1126.0F), false);
      Float float0 = new Float((-1.0F));
      HomeMaterial homeMaterial0 = new HomeMaterial("com.eteks.sweethome3d.tools.URLContent", (Integer) null, homeTexture0, float0);
      Integer integer0 = new Integer(557);
      HomeMaterial homeMaterial1 = new HomeMaterial("com.eteks.sweethome3d.tools.URLContent", integer0, homeTexture0, float0);
      boolean boolean0 = homeMaterial0.equals(homeMaterial1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Integer integer0 = new Integer(1324);
      Class<HomeMaterial> class0 = HomeMaterial.class;
      ResourceURLContent resourceURLContent0 = new ResourceURLContent(class0, "", true);
      CatalogTexture catalogTexture0 = new CatalogTexture((String) null, "/\"", resourceURLContent0, (-2968.4675F), 1324, "", true);
      HomeTexture homeTexture0 = new HomeTexture(catalogTexture0, 1.0F, 620.0F, 1.0F, 1.0F, true);
      Float float0 = new Float((-2968.4675F));
      HomeMaterial homeMaterial0 = new HomeMaterial("/\"", "com.eteks.sweethome3d.model.HomeMaterial", integer0, homeTexture0, float0);
      HomeMaterial homeMaterial1 = new HomeMaterial("/\"", "", integer0, homeTexture0, float0);
      boolean boolean0 = homeMaterial0.equals(homeMaterial1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Integer integer0 = new Integer(1324);
      Class<HomeMaterial> class0 = HomeMaterial.class;
      ResourceURLContent resourceURLContent0 = new ResourceURLContent(class0, "", true);
      CatalogTexture catalogTexture0 = new CatalogTexture((String) null, "/\"", resourceURLContent0, (-2968.4675F), 1324, "", true);
      HomeTexture homeTexture0 = new HomeTexture(catalogTexture0, 1.0F, 620.0F, 1.0F, 1.0F, true);
      Float float0 = new Float((-2968.4675F));
      HomeMaterial homeMaterial0 = new HomeMaterial("/\"", "com.eteks.sweethome3d.model.HomeMaterial", integer0, homeTexture0, float0);
      HomeMaterial homeMaterial1 = new HomeMaterial("/\"", integer0, homeTexture0, float0);
      boolean boolean0 = homeMaterial0.equals(homeMaterial1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Integer integer0 = new Integer(2);
      URL uRL0 = MockURL.getFtpExample();
      SimpleURLContent simpleURLContent0 = new SimpleURLContent(uRL0);
      CatalogTexture catalogTexture0 = new CatalogTexture("}.", simpleURLContent0, 1194.8F, 2, true);
      HomeTexture homeTexture0 = new HomeTexture(catalogTexture0, 2);
      Float float0 = new Float(0.0);
      HomeMaterial homeMaterial0 = new HomeMaterial("}.", integer0, homeTexture0, float0);
      HomeMaterial homeMaterial1 = new HomeMaterial((String) null, integer0, homeTexture0, float0);
      boolean boolean0 = homeMaterial0.equals(homeMaterial1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Float float0 = new Float(3245.2512F);
      HomeMaterial homeMaterial0 = new HomeMaterial("/\"", "*-5.u}i2^", (Integer) null, (HomeTexture) null, float0);
      Integer integer0 = homeMaterial0.getColor();
      HomeMaterial homeMaterial1 = new HomeMaterial("*-5.u}i2^", integer0, (HomeTexture) null, float0);
      boolean boolean0 = homeMaterial0.equals(homeMaterial1);
      assertFalse(homeMaterial1.equals((Object)homeMaterial0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Integer integer0 = new Integer((-736));
      Float float0 = new Float((-651.0772F));
      HomeMaterial homeMaterial0 = new HomeMaterial("", "", integer0, (HomeTexture) null, float0);
      boolean boolean0 = homeMaterial0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Integer integer0 = new Integer(183);
      CatalogTexture catalogTexture0 = new CatalogTexture("com.eteks.sweethome3d.model.HomeMaterial", "com.eteks.sweethome3d.model.HomeMaterial", (Content) null, 183, 183, "", true);
      HomeTexture homeTexture0 = new HomeTexture(catalogTexture0, 3116.332F, true);
      HomeMaterial homeMaterial0 = new HomeMaterial("com.eteks.sweethome3d.model.HomeMaterial", integer0, homeTexture0, (Float) null);
      homeMaterial0.hashCode();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CatalogTexture catalogTexture0 = new CatalogTexture("6s$>E*+^Y;g!`o28", (Content) null, (-1.0F), (-1.0F), false);
      HomeTexture homeTexture0 = new HomeTexture(catalogTexture0, (-1.0F), false);
      Float float0 = new Float(0.0F);
      HomeMaterial homeMaterial0 = new HomeMaterial("com.eteks.sweethome3d.model.HomeMaterial", (Integer) null, homeTexture0, float0);
      homeMaterial0.hashCode();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Integer integer0 = new Integer((-736));
      Float float0 = new Float((-651.0772F));
      HomeMaterial homeMaterial0 = new HomeMaterial("", "", integer0, (HomeTexture) null, float0);
      homeMaterial0.hashCode();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Integer integer0 = new Integer(553);
      URL uRL0 = MockURL.getFileExample();
      ResourceURLContent resourceURLContent0 = new ResourceURLContent(uRL0, true);
      CatalogTexture catalogTexture0 = new CatalogTexture("", (String) null, resourceURLContent0, 0.0F, 0.0F, (String) null);
      HomeTexture homeTexture0 = new HomeTexture(catalogTexture0, 0.0F, true);
      Float float0 = new Float(5050.571F);
      HomeMaterial homeMaterial0 = new HomeMaterial((String) null, "", integer0, homeTexture0, float0);
      homeMaterial0.hashCode();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Integer integer0 = new Integer((-736));
      Float float0 = new Float((-651.0772F));
      HomeMaterial homeMaterial0 = new HomeMaterial("", "", integer0, (HomeTexture) null, float0);
      String string0 = homeMaterial0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Integer integer0 = new Integer((-736));
      Float float0 = new Float((-651.0772F));
      HomeMaterial homeMaterial0 = new HomeMaterial("", "", integer0, (HomeTexture) null, float0);
      HomeTexture homeTexture0 = homeMaterial0.getTexture();
      assertNull(homeTexture0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Integer integer0 = new Integer((-4222));
      HomeMaterial homeMaterial0 = new HomeMaterial("", integer0, (HomeTexture) null, (Float) null);
      String string0 = homeMaterial0.getKey();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Float float0 = new Float(3238.3098F);
      HomeMaterial homeMaterial0 = new HomeMaterial("*-5.u}i2^", (Integer) null, (HomeTexture) null, float0);
      Float float1 = homeMaterial0.getShininess();
      assertEquals(3238.3098F, (float)float1, 0.01F);
  }
}
