/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 28 03:39:31 GMT 2022
 */

package com.eteks.sweethome3d.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.eteks.sweethome3d.model.CatalogLight;
import com.eteks.sweethome3d.model.Content;
import com.eteks.sweethome3d.model.HomeLight;
import com.eteks.sweethome3d.model.LightSource;
import com.eteks.sweethome3d.tools.ResourceURLContent;
import com.eteks.sweethome3d.tools.TemporaryURLContent;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.URL;
import java.net.URLStreamHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HomeLight_ESTest extends HomeLight_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[4];
      Long long0 = new Long(2472L);
      Float float0 = new Float(2.502817F);
      URLStreamHandler uRLStreamHandler0 = mock(URLStreamHandler.class, new ViolatedAssumptionAnswer());
      URL uRL0 = MockURL.URL("qYv}*_[:w[A&z}Ds", "editorSubFolder", 32, "I=~g/&#,h75", uRLStreamHandler0);
      ResourceURLContent resourceURLContent0 = new ResourceURLContent(uRL0, false);
      LightSource[] lightSourceArray0 = new LightSource[5];
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      CatalogLight catalogLight0 = new CatalogLight("", "Linux", "Linux", "VALUE_ADDED_TAX_PERCENTAGE", stringArray0, long0, float0, resourceURLContent0, resourceURLContent0, resourceURLContent0, 0.0F, 2.502817F, 2.502817F, 0.0F, 0.0F, false, lightSourceArray0, "", (float[][]) null, true, long0, "I=~g/&#,h75", true, true, true, false, bigDecimal0, bigDecimal0, "");
      HomeLight homeLight0 = new HomeLight("/>y$MD", catalogLight0);
      homeLight0.setLightSources(lightSourceArray0);
      assertEquals(0.5F, homeLight0.getPower(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[5];
      Long long0 = new Long((-1L));
      Float float0 = new Float(2159.91F);
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ResourceURLContent resourceURLContent0 = new ResourceURLContent(classLoader0, "");
      LightSource[] lightSourceArray0 = new LightSource[0];
      float[][] floatArray0 = new float[8][6];
      BigDecimal bigDecimal0 = new BigDecimal((-1L));
      CatalogLight catalogLight0 = new CatalogLight((String) null, "i%Wa(4axgN(jy", "light", "|[q3;-^\"p-,R3o6BI*", stringArray0, long0, float0, resourceURLContent0, resourceURLContent0, resourceURLContent0, 2691.0F, 0.0F, 2.0F, 0.0F, false, lightSourceArray0, "", floatArray0, "T1&[GST?", false, true, true, bigDecimal0, bigDecimal0, "|[q3;-^\"p-,R3o6BI*");
      HomeLight homeLight0 = new HomeLight(catalogLight0);
      LightSource[] lightSourceArray1 = homeLight0.getLightSources();
      assertEquals(0.5F, homeLight0.getPower(), 0.01F);
      assertSame(lightSourceArray1, lightSourceArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[10];
      Long long0 = new Long((-1331L));
      Float float0 = new Float((-1728.2F));
      LightSource[] lightSourceArray0 = new LightSource[1];
      float[][] floatArray0 = new float[4][8];
      BigDecimal bigDecimal0 = new BigDecimal(0.0);
      CatalogLight catalogLight0 = new CatalogLight("com.eteks.sweethome3d.model.HomeLight$Property", "\"+2", "com.eteks.sweethome3d.model.HomeLight$Property", "\"+2", stringArray0, long0, float0, (Content) null, (Content) null, (Content) null, 3019.682F, (-1331L), (-1331L), (-1728.2F), 0.0F, false, lightSourceArray0, "Y4P>#}", floatArray0, true, long0, "com.eteks.sweethome3d.model.HomeLight$Property", false, false, true, false, bigDecimal0, bigDecimal0, "com.eteks.sweethome3d.model.HomeLight$Property");
      HomeLight homeLight0 = new HomeLight(catalogLight0);
      HomeLight homeLight1 = new HomeLight("com.eteks.sweethome3d.model.HomeLight$Property", homeLight0);
      assertEquals(0.5F, homeLight1.getPower(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[10];
      Long long0 = new Long((-1331L));
      Float float0 = new Float((-1728.2F));
      LightSource[] lightSourceArray0 = new LightSource[1];
      float[][] floatArray0 = new float[4][8];
      BigDecimal bigDecimal0 = new BigDecimal(0.0);
      CatalogLight catalogLight0 = new CatalogLight("com.eteks.sweethome3d.model.HomeLight$Property", "\"+2", "com.eteks.sweethome3d.model.HomeLight$Property", "\"+2", stringArray0, long0, float0, (Content) null, (Content) null, (Content) null, 3019.682F, (-1331L), (-1331L), (-1728.2F), 0.0F, false, lightSourceArray0, "Y4P>#}", floatArray0, true, long0, "com.eteks.sweethome3d.model.HomeLight$Property", false, false, true, false, bigDecimal0, bigDecimal0, "com.eteks.sweethome3d.model.HomeLight$Property");
      HomeLight homeLight0 = new HomeLight(catalogLight0);
      assertEquals(0.5F, homeLight0.getPower(), 0.01F);
      
      homeLight0.setPower(0.0F);
      assertEquals(0.0F, homeLight0.getPower(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[7];
      Long long0 = new Long((-1L));
      Float float0 = new Float(0.0F);
      TemporaryURLContent temporaryURLContent0 = new TemporaryURLContent((URL) null);
      LightSource[] lightSourceArray0 = new LightSource[0];
      CatalogLight catalogLight0 = new CatalogLight("", ",~v&(=\"CT&tS'", "", "", stringArray0, long0, float0, temporaryURLContent0, temporaryURLContent0, temporaryURLContent0, 0.0F, (-27.0F), (-27.0F), 2565.363F, (-488.6756F), true, lightSourceArray0, ",~v&(=\"CT&tS'", (float[][]) null, false, "", true, true, false, (BigDecimal) null, (BigDecimal) null, "");
      HomeLight homeLight0 = new HomeLight("", catalogLight0);
      float float1 = homeLight0.getPower();
      assertEquals(0.5F, float1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[5];
      Long long0 = new Long((-1L));
      Float float0 = new Float(2159.91F);
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ResourceURLContent resourceURLContent0 = new ResourceURLContent(classLoader0, "");
      LightSource[] lightSourceArray0 = new LightSource[0];
      float[][] floatArray0 = new float[8][6];
      BigDecimal bigDecimal0 = new BigDecimal((-1L));
      CatalogLight catalogLight0 = new CatalogLight((String) null, "i%Wa(4axgN(jy", "light", "|[q3;-^\"p-,R3o6BI*", stringArray0, long0, float0, resourceURLContent0, resourceURLContent0, resourceURLContent0, 2691.0F, 0.0F, 2.0F, 0.0F, false, lightSourceArray0, "", floatArray0, "T1&[GST?", false, true, true, bigDecimal0, bigDecimal0, "|[q3;-^\"p-,R3o6BI*");
      HomeLight homeLight0 = new HomeLight(catalogLight0);
      HomeLight homeLight1 = homeLight0.clone();
      assertEquals(0.5F, homeLight1.getPower(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LightSource[] lightSourceArray0 = new LightSource[7];
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      CatalogLight catalogLight0 = new CatalogLight("", "3T+@9=-b$Pp", "", (Content) null, (Content) null, (Content) null, (-1070.7369F), (-1070.7369F), (-1070.7369F), (-1070.7369F), true, lightSourceArray0, (float[][]) null, "3T+@9=-b$Pp", false, true, false, bigDecimal0, bigDecimal0);
      HomeLight homeLight0 = new HomeLight(catalogLight0);
      homeLight0.setPower(0.5F);
      assertTrue(homeLight0.isVisible());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String[] stringArray0 = new String[8];
      Long long0 = new Long(2022L);
      Float float0 = new Float(2151.243F);
      LightSource[] lightSourceArray0 = new LightSource[1];
      float[][] floatArray0 = new float[5][7];
      BigInteger bigInteger0 = BigInteger.ONE;
      BigDecimal bigDecimal0 = new BigDecimal(bigInteger0);
      CatalogLight catalogLight0 = new CatalogLight("", "", "", "", stringArray0, long0, float0, (Content) null, (Content) null, (Content) null, 2151.243F, 2151.243F, 2151.243F, 0.5F, 2151.243F, false, lightSourceArray0, "Bqe8e~cL", floatArray0, false, "Bqe8e~cL", false, false, false, bigDecimal0, bigDecimal0, "Bqe8e~cL");
      HomeLight homeLight0 = new HomeLight(")mF}?Iw70", catalogLight0);
      LightSource[] lightSourceArray1 = new LightSource[0];
      homeLight0.setLightSources(lightSourceArray1);
      homeLight0.setLightSources(lightSourceArray0);
      assertEquals(0.5F, homeLight0.getPower(), 0.01F);
  }
}
