/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 28 03:57:15 GMT 2022
 */

package com.eteks.sweethome3d.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.eteks.sweethome3d.model.Transformation;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Transformation_ESTest extends Transformation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      float[][] floatArray0 = new float[2][4];
      Transformation transformation0 = new Transformation("", floatArray0);
      float[][] floatArray1 = new float[3][6];
      float[] floatArray2 = new float[5];
      floatArray2[0] = (-1.0F);
      floatArray1[0] = floatArray2;
      Transformation transformation1 = new Transformation("", floatArray1);
      boolean boolean0 = transformation0.equals(transformation1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      float[][] floatArray0 = new float[1][7];
      Transformation transformation0 = new Transformation("*dY7^Jln", floatArray0);
      Transformation transformation1 = new Transformation("LhvESEZw.]%k", floatArray0);
      boolean boolean0 = transformation0.equals(transformation1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      float[][] floatArray0 = new float[1][7];
      Transformation transformation0 = new Transformation("*dY7^Jln", floatArray0);
      boolean boolean0 = transformation0.equals(transformation0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      float[][] floatArray0 = new float[0][0];
      Transformation transformation0 = new Transformation("ges6c;I~1]^", floatArray0);
      boolean boolean0 = transformation0.equals("ges6c;I~1]^");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Transformation transformation0 = new Transformation("", (float[][]) null);
      transformation0.hashCode();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Transformation transformation0 = new Transformation("", (float[][]) null);
      // Undeclared exception!
      try { 
        transformation0.getMatrix();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.eteks.sweethome3d.model.Transformation", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Transformation transformation0 = new Transformation("t8[RXiOfBf", (float[][]) null);
      String string0 = transformation0.getName();
      assertEquals("t8[RXiOfBf", string0);
  }
}
