/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 28 00:53:06 GMT 2022
 */

package com.jagrosh.jmusicbot.audio;

import org.junit.Test;
import static org.junit.Assert.*;
import com.jagrosh.jmusicbot.Bot;
import com.jagrosh.jmusicbot.audio.AloneInVoiceHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AloneInVoiceHandler_ESTest extends AloneInVoiceHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AloneInVoiceHandler aloneInVoiceHandler0 = new AloneInVoiceHandler((Bot) null);
  }
}
