/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 28 03:12:22 GMT 2022
 */

package com.eteks.sweethome3d.io;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.eteks.sweethome3d.io.DefaultUserPreferences;
import com.eteks.sweethome3d.io.HomeContentContext;
import com.eteks.sweethome3d.model.Content;
import com.eteks.sweethome3d.model.UserPreferences;
import java.net.URL;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HomeContentContext_ESTest extends HomeContentContext_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HomeContentContext homeContentContext0 = null;
      try {
        homeContentContext0 = new HomeContentContext((URL) null, (UserPreferences) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.net.MockURL", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      DefaultUserPreferences defaultUserPreferences0 = new DefaultUserPreferences();
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "beta");
      HomeContentContext homeContentContext0 = new HomeContentContext(uRL0, defaultUserPreferences0, true);
      assertFalse(homeContentContext0.containsCheckedContents());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      DefaultUserPreferences defaultUserPreferences0 = new DefaultUserPreferences();
      HomeContentContext homeContentContext0 = new HomeContentContext(uRL0, defaultUserPreferences0, true);
      boolean boolean0 = homeContentContext0.containsCheckedContents();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      HomeContentContext homeContentContext0 = new HomeContentContext(uRL0, (UserPreferences) null, false);
      List<Content> list0 = homeContentContext0.getInvalidContents();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      HomeContentContext homeContentContext0 = new HomeContentContext(uRL0, (UserPreferences) null, false);
      boolean boolean0 = homeContentContext0.containsInvalidContents();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      DefaultUserPreferences defaultUserPreferences0 = new DefaultUserPreferences();
      HomeContentContext homeContentContext0 = new HomeContentContext(uRL0, defaultUserPreferences0, true);
      // Undeclared exception!
      try { 
        homeContentContext0.lookupContent("Missing entry name");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.eteks.sweethome3d.tools.URLContent", e);
      }
  }
}
